sudo: required

service:
  - docker

before_install:
  - docker build -t bushjdo/docker_reactjs_firsttime -f Dockerfile.dev .

script:
  - docker run bushjdo/docker_reactjs_firsttime npm run test -- --coverage
